import { combineEpics } from 'redux-observable';
import { SignInEpic, TermsAndConditionsEpic } from './SignInEpic';
import {
	GetAllHashtagsEpic,
	GetAllCategoriesEpic,
	AddHashTagEpic,
	EditHashTagEpic,
	AddCategoryEpic,
	EditCategoryEpic,
	DeleteHashTagEpic,
	DeleteCategoryEpic,
	GetAllEventCategoriesEpic,
	GetAllMusicCategoriesEpic,
	DeleteEventCategoryEpic,
	DeleteMusicCategoryEpic,
	AddEventCategoryEpic,
	AddMusicCategoryEpic,
	EditEventCategoryEpic,
	EditMusicCategoryEpic,
	GetAllEventEpic,
	AddEventEpic,
	DeleteEventEpic,
	GetAllInvitEventEpic,
	DeleteIvitEventEpic,
} from './DashboardEpic';
import {
	
	GetUserListEpic,
	EditUserEpic,
	AddUserEpic,
	DeleteUserEpic,
	GetUserDetailsEpic,
	ResumeSuspendUserEpic,
	GetDjUserListEpic,
	GetDjUserDetailsEpic,
} from './UserManagementEpic';
import { AddEditContentEpic, getContentDataEpic } from './ContentManageEpic';
import {
	GetChallengeListEpic,
	EditChallengeEpic,
	AddChallengeEpic,
	DeleteChallengeEpic,
	GetChallengeDetailsEpic,
	GetUserChallengeListEpic,
	DeleteUserChallengeEpic,
	GetUserChallengeDetailsEpic,
} from './ChallengeManageEpic';
import { GetPostListEpic, DeletePostEpic, GetPostDetailsEpic } from './PostManageEpic';
import { UpdateAdminProfileEpic, GetAdminProfileEpic, ForgotPassEpic } from './ProfileEpic';

const rootEpic = combineEpics(
	GetAllEventEpic,
	GetDjUserDetailsEpic,
	GetDjUserListEpic,
	EditEventCategoryEpic,
	EditMusicCategoryEpic,
	AddEventCategoryEpic,
	AddMusicCategoryEpic,
	DeleteEventCategoryEpic,
	DeleteMusicCategoryEpic,
	GetAllEventCategoriesEpic,
	GetAllMusicCategoriesEpic,
	AddEditContentEpic,
	getContentDataEpic,
	TermsAndConditionsEpic,
	SignInEpic,
	EditUserEpic,
	AddUserEpic,
	UpdateAdminProfileEpic,
	GetAdminProfileEpic,
	ForgotPassEpic,
	GetAllHashtagsEpic,
	GetAllCategoriesEpic,
	AddHashTagEpic,
	EditHashTagEpic,
	AddCategoryEpic,
	EditCategoryEpic,
	DeleteHashTagEpic,
	DeleteCategoryEpic,
	GetUserListEpic,
	DeleteUserEpic,
	GetUserDetailsEpic,
	GetChallengeListEpic,
	EditChallengeEpic,
	AddChallengeEpic,
	DeleteChallengeEpic,
	GetChallengeDetailsEpic,
	GetPostListEpic,
	DeletePostEpic,
	GetPostDetailsEpic,
	GetUserChallengeListEpic,
	DeleteUserChallengeEpic,
	GetUserChallengeDetailsEpic,
	ResumeSuspendUserEpic,
	AddEventEpic,
	DeleteEventEpic,
	GetAllInvitEventEpic,
	DeleteIvitEventEpic
);
export default rootEpic;
