export const SIGN_IN = 'SIGN_IN';
export const SIGN_IN_SUCCESS = 'SIGN_IN_SUCCESS';
export const SIGN_IN_FAILURE = 'SIGN_IN_FAILURE';

export const ADD_EVENT  ='ADD_EVENT';
export const ADD_EVENT_SUCCESS  ='ADD_EVENT_SUCCESS';
export const ADD_EVENT_FAILURE  ='ADD_EVENT_FAILURE';

export const DELETE_EVENT  ='DELETE_EVENT';
export const DELETE_EVENT_SUCCESS  ='DELETE_EVENT_SUCCESS';
export const DELETE_EVENT_FAILURE  ='DELETE_EVENT_FAILURE';

export const DELETE_INVIT_EVENT  ='DELETE_INVIT_EVENT';
export const DELETE_INVIT_EVENT_SUCCESS  ='DELETE_INVIT_EVENT_SUCCESS';
export const DELETE_INVIT_EVENT_FAILURE  ='DELETE_INVIT_EVENT_FAILURE';

export const TERMS_AND_CONDITIONS = 'TERMS_AND_CONDITIONS';
export const TERMS_AND_CONDITIONS_SUCCESS = 'TERMS_AND_CONDITIONS_SUCCESS';
export const TERMS_AND_CONDITIONS_FAILURE = 'TERMS_AND_CONDITIONS_FAILURE';

export const GET_HASHTAG_LIST = 'GET_HASHTAG_LIST';
export const GET_HASHTAG_LIST_SUCCESS = 'GET_HASHTAG_LIST_SUCCESS';
export const GET_HASHTAG_LIST_FAILURE = 'GET_HASHTAG_LIST_FAILURE';

export const GET_CATEGORY_LIST = 'GET_CATEGORY_LIST';
export const GET_CATEGORY_LIST_SUCCESS = 'GET_CATEGORY_LIST_SUCCESS';
export const GET_CATEGORY_LIST_FAILURE = 'GET_CATEGORY_LIST_FAILURE';

export const DELETE_HASHTAG = 'DELETE_HASHTAG';
export const DELETE_HASHTAG_SUCCESS = 'DELETE_HASHTAG_SUCCESS';
export const DELETE_HASHTAG_FAILURE = 'DELETE_HASHTAG_FAILURE';

export const DELETE_CATEGORY = 'DELETE_CATEGORY';
export const DELETE_CATEGORY_SUCCESS = 'DELETE_CATEGORY_SUCCESS';
export const DELETE_CATEGORY_FAILURE = 'DELETE_CATEGORY_FAILURE';

export const ADD_HASHTAG = 'ADD_HASHTAG';
export const ADD_HASHTAG_SUCCESS = 'ADD_HASHTAG_SUCCESS';
export const ADD_HASHTAG_FAILURE = 'ADD_HASHTAG_FAILURE';

export const EDIT_HASHTAG = 'EDIT_HASHTAG';
export const EDIT_HASHTAG_SUCCESS = 'EDIT_HASHTAG_SUCCESS';
export const EDIT_HASHTAG_FAILURE = 'EDIT_HASHTAG_FAILURE';

export const ADD_CATEGORY = 'ADD_CATEGORY';
export const ADD_CATEGORY_SUCCESS = 'ADD_CATEGORY_SUCCESS';
export const ADD_CATEGORY_FAILURE = 'ADD_CATEGORY_FAILURE';

export const EDIT_CATEGORY = 'EDIT_CATEGORY';
export const EDIT_CATEGORY_SUCCESS = 'EDIT_CATEGORY_SUCCESS';
export const EDIT_CATEGORY_FAILURE = 'EDIT_CATEGORY_FAILURE';

export const GET_MESSAGE_DETAILS = 'GET_MESSAGE_DETAILS';
export const GET_MESSAGE_DETAILS_SUCCESS = 'GET_MESSAGE_DETAILS_SUCCESS';
export const GET_MESSAGE_DETAILS_FAILURE = 'GET_MESSAGE_DETAILS_FAILURE';

export const SEND_ADMIN_MESSAGE_RESPONSE = 'SEND_ADMIN_MESSAGE_RESPONSE';
export const SEND_ADMIN_MESSAGE_RESPONSE_SUCCESS = 'SEND_ADMIN_MESSAGE_RESPONSE_SUCCESS';
export const SEND_ADMIN_MESSAGE_RESPONSE_FAILURE = 'SEND_ADMIN_MESSAGE_RESPONSE_FAILURE';

export const GET_QUERY_USER_LIST = 'GET_QUERY_USER_LIST';
export const GET_QUERY_USER_LIST_SUCCESS = 'GET_QUERY_USER_LIST_SUCCESS';
export const GET_QUERY_USER_LIST_FAILURE = 'GET_QUERY_USER_LIST_FAILURE';

export const GET_QUERY_DETAILS = 'GET_QUERY_DETAILS';
export const GET_QUERY_DETAILS_SUCCESS = 'GET_QUERY_DETAILS_SUCCESS';
export const GET_QUERY_DETAILS_FAILURE = 'GET_QUERY_DETAILS_FAILURE';

export const SEND_ADMIN_QUERY_RESPONSE = 'SEND_ADMIN_QUERY_RESPONSE';
export const SEND_ADMIN_QUERY_RESPONSE_SUCCESS = 'SEND_ADMIN_QUERY_RESPONSE_SUCCESS';
export const SEND_ADMIN_QUERY_RESPONSE_FAILURE = 'SEND_ADMIN_QUERY_RESPONSE_FAILURE';

export const GET_MESSAGE_LIST = 'GET_MESSAGE_LIST';
export const GET_MESSAGE_LIST_SUCCESS = 'GET_MESSAGE_LIST_SUCCESS';
export const GET_MESSAGE_LIST_FAILURE = 'GET_MESSAGE_LIST_FAILURE';

export const GET_USER_DETAILS = 'GET_USER_DETAILS';
export const GET_DJ_USER_DETAILS = 'GET_DJ_USER_DETAILS';
export const GET_USER_DETAILS_SUCCESS = 'GET_USER_DETAILS_SUCCESS';
export const GET_USER_DETAILS_FAILURE = 'GET_USER_DETAILS_FAILURE';

export const GET_USER_LIST = 'GET_USER_LIST';
export const GET_DJ_USER_LIST = 'GET_DJ_USER_LIST';
export const GET_USER_LIST_SUCCESS = 'GET_USER_LIST_SUCCESS';
export const GET_USER_LIST_FAILURE = 'GET_USER_LIST_FAILURE';

export const DELETE_USER = 'DELETE_USER';
export const DELETE_USER_SUCCESS = 'DELETE_USER_SUCCESS';
export const DELETE_USER_FAILURE = 'DELETE_USER_FAILURE';

export const EDIT_USER = 'EDIT_USER';
export const EDIT_USER_SUCCESS = 'EDIT_USER_SUCCESS';
export const EDIT_USER_FAILURE = 'EDIT_USER_FAILURE';

export const ADD_USER = 'ADD_USER';
export const ADD_USER_SUCCESS = 'ADD_USER_SUCCESS';
export const ADD_USER_FAILURE = 'ADD_USER_FAILURE';

export const SEND_ADMIN_MESSAGE = 'SEND_ADMIN_MESSAGE';
export const SEND_ADMIN_MESSAGE_SUCCESS = 'SEND_ADMIN_MESSAGE_SUCCESS';
export const SEND_ADMIN_MESSAGE_FAILURE = 'SEND_ADMIN_MESSAGE_FAILURE';

export const OPEN_CLOSE_SUPPORT = 'OPEN_CLOSE_SUPPORT';
export const OPEN_CLOSE_SUPPORT_SUCCESS = 'OPEN_CLOSE_SUPPORT_SUCCESS';
export const OPEN_CLOSE_SUPPORT_FAILURE = 'OPEN_CLOSE_SUPPORT_FAILURE';

export const ADD_EDIT_CONTENT = 'ADD_EDIT_CONTENT';
export const ADD_EDIT_CONTENT_SUCCESS = 'ADD_EDIT_CONTENT_SUCCESS';
export const ADD_EDIT_CONTENT_FAILURE = 'ADD_EDIT_CONTENT_FAILURE';

export const GET_CONTENT_DATA = 'GET_CONTENT_DATA';
export const GET_CONTENT_DATA_SUCCESS = 'GET_CONTENT_DATA_SUCCESS';
export const GET_CONTENT_DATA_FAILURE = 'GET_CONTENT_DATA_FAILURE';

export const UPDATE_ADMIN_PROFILE = 'UPDATE_ADMIN_PROFILE';
export const UPDATE_ADMIN_PROFILE_SUCCESS = 'UPDATE_ADMIN_PROFILE_SUCCESS';
export const UPDATE_ADMIN_PROFILE_FAILURE = 'UPDATE_ADMIN_PROFILE_FAILURE';

export const GET_ADMIN_PROFILE = 'GET_ADMIN_PROFILE';
export const GET_ADMIN_PROFILE_SUCCESS = 'GET_ADMIN_PROFILE_SUCCESS';
export const GET_ADMIN_PROFILE_FAILURE = 'GET_ADMIN_PROFILE_FAILURE';

export const FORGOT_PASSWORD = 'FORGOT_PASSWORD';
export const FORGOT_PASSWORD_SUCCESS = 'FORGOT_PASSWORD_SUCCESS';
export const FORGOT_PASSWORD_FAILURE = 'FORGOT_PASSWORD_FAILURE';

export const REMEMBER_ME = 'REMEMBER_ME';

export const UPDATE_HOME_DATA = 'UPDATE_HOME_DATA';
export const UPDATE_HOME_DATA_SUCCESS = 'UPDATE_HOME_DATA_SUCCESS';
export const UPDATE_HOME_DATA_FAILURE = 'UPDATE_HOME_DATA_FAILURE';

export const GET_HOME_DATA = 'GET_HOME_DATA';
export const GET_HOME_DATA_SUCCESS = 'GET_HOME_DATA_SUCCESS';
export const GET_HOME_DATA_FAILURE = 'GET_HOME_DATA_FAILURE';
export const TOGGLE_SUBNAV = 'TOGGLE_SUBNAV';

export const GET_CHALLENGE_LIST = 'GET_CHALLENGE_LIST';
export const GET_CHALLENGE_LIST_SUCCESS = 'GET_CHALLENGE_LIST_SUCCESS';
export const GET_CHALLENGE_LIST_FAILURE = 'GET_CHALLENGE_LIST_FAILURE';

export const ADD_CHALLENGE = 'ADD_CHALLENGE';
export const ADD_CHALLENGE_SUCCESS = 'ADD_CHALLENGE_SUCCESS';
export const ADD_CHALLENGE_FAILURE = 'ADD_CHALLENGE_FAILURE';

export const EDIT_CHALLENGE = 'EDIT_CHALLENGE';
export const EDIT_CHALLENGE_SUCCESS = 'EDIT_CHALLENGE_SUCCESS';
export const EDIT_CHALLENGE_FAILURE = 'EDIT_CHALLENGE_FAILURE';

export const DELETE_CHALLENGE = 'DELETE_CHALLENGE';
export const DELETE_CHALLENGE_SUCCESS = 'DELETE_CHALLENGE_SUCCESS';
export const DELETE_CHALLENGE_FAILURE = 'DELETE_CHALLENGE_FAILURE';

export const GET_CHALLENGE_DETAILS = 'GET_CHALLENGE_DETAILS';
export const GET_CHALLENGE_DETAILS_SUCCESS = 'GET_CHALLENGE_DETAILS_SUCCESS';
export const GET_CHALLENGE_DETAILS_FAILURE = 'GET_CHALLENGE_DETAILS_FAILURE';

export const GET_POST_LIST = 'GET_POST_LIST';
export const GET_POST_LIST_SUCCESS = 'GET_POST_LIST_SUCCESS';
export const GET_POST_LIST_FAILURE = 'GET_POST_LIST_FAILURE';

export const DELETE_POST = 'DELETE_POST';
export const DELETE_POST_SUCCESS = 'DELETE_POST_SUCCESS';
export const DELETE_POST_FAILURE = 'DELETE_POST_FAILURE';

export const GET_POST_DETAILS = 'GET_POST_DETAILS';
export const GET_POST_DETAILS_SUCCESS = 'GET_POST_DETAILS_SUCCESS';
export const GET_POST_DETAILS_FAILURE = 'GET_POST_DETAILS_FAILURE';

export const GET_USER_CHALLENGE_LIST = 'GET_USER_CHALLENGE_LIST';
export const GET_USER_CHALLENGE_LIST_SUCCESS = 'GET_USER_CHALLENGE_LIST_SUCCESS';
export const GET_USER_CHALLENGE_LIST_FAILURE = 'GET_USER_CHALLENGE_LIST_FAILURE';

export const DELETE_USER_CHALLENGE = 'DELETE_USER_CHALLENGE';
export const DELETE_USER_CHALLENGE_SUCCESS = 'DELETE_USER_CHALLENGE_SUCCESS';
export const DELETE_USER_CHALLENGE_FAILURE = 'DELETE_USER_CHALLENGE_FAILURE';

export const GET_USER_CHALLENGE_DETAILS = 'GET_USER_CHALLENGE_DETAILS';
export const GET_USER_CHALLENGE_DETAILS_SUCCESS = 'GET_USER_CHALLENGE_DETAILS_SUCCESS';
export const GET_USER_CHALLENGE_DETAILS_FAILURE = 'GET_USER_CHALLENGE_DETAILS_FAILURE';

export const RESUME_SUSPEND_USER = 'RESUME_SUSPEND_USER';
export const RESUME_SUSPEND_USER_SUCCESS = 'RESUME_SUSPEND_USER_SUCCESS';
export const RESUME_SUSPEND_USER_FAILURE = 'RESUME_SUSPEND_USER_FAILURE';

export const GET_EVENT_CATEGORY_LIST = 'GET_EVENT_CATEGORY_LIST';
export const GET_EVENT_CATEGORY_LIST_SUCCESS = 'GET_EVENT_CATEGORY_LIST_SUCCESS';
export const GET_EVENT_CATEGORY_LIST_FAILURE = 'GET_EVENT_CATEGORY_LIST_FAILURE';

export const DELETE_EVENT_CATEGORY = 'DELETE_EVENT_CATEGORY';
export const DELETE_EVENT_CATEGORY_SUCCESS = 'DELETE_EVENT_CATEGORY_SUCCESS';
export const DELETE_EVENT_CATEGORY_FAILURE = 'DELETE_EVENT_CATEGORY_FAILURE';

export const ADD_EVENT_CATEGORY = 'ADD_EVENT_CATEGORY';
export const ADD_EVENT_CATEGORY_SUCCESS = 'ADD_EVENT_CATEGORY_SUCCESS';
export const ADD_EVENT_CATEGORY_FAILURE = 'ADD_EVENT_CATEGORY_FAILURE';

export const EDIT_EVENT_CATEGORY = 'EDIT_EVENT_CATEGORY';
export const EDIT_EVENT_CATEGORY_SUCCESS = 'EDIT_EVENT_CATEGORY_SUCCESS';
export const EDIT_EVENT_CATEGORY_FAILURE = 'EDIT_EVENT_CATEGORY_FAILURE';

export const GET_MUSIC_CATEGORY_LIST = 'GET_MUSIC_CATEGORY_LIST';
export const GET_MUSIC_CATEGORY_LIST_SUCCESS = 'GET_MUSIC_CATEGORY_LIST_SUCCESS';
export const GET_MUSIC_CATEGORY_LIST_FAILURE = 'GET_MUSIC_CATEGORY_LIST_FAILURE';

export const DELETE_MUSIC_CATEGORY = 'DELETE_MUSIC_CATEGORY';
export const DELETE_MUSIC_CATEGORY_SUCCESS = 'DELETE_MUSIC_CATEGORY_SUCCESS';
export const DELETE_MUSIC_CATEGORY_FAILURE = 'DELETE_MUSIC_CATEGORY_FAILURE';

export const ADD_MUSIC_CATEGORY = 'ADD_MUSIC_CATEGORY';
export const ADD_MUSIC_CATEGORY_SUCCESS = 'ADD_MUSIC_CATEGORY_SUCCESS';
export const ADD_MUSIC_CATEGORY_FAILURE = 'ADD_MUSIC_CATEGORY_FAILURE';

export const EDIT_MUSIC_CATEGORY = 'EDIT_MUSIC_CATEGORY';
export const EDIT_MUSIC_CATEGORY_SUCCESS = 'EDIT_MUSIC_CATEGORY_SUCCESS';
export const EDIT_MUSIC_CATEGORY_FAILURE = 'EDIT_MUSIC_CATEGORY_FAILURE';


export const GET_EVENT_LIST = 'GET_EVENT_LIST';
export const GET_EVENT_LIST_SUCCESS = 'GET_EVENT_LIST_SUCCESS';
export const GET_EVENT_LIST_FAILURE = 'GET_EVENT_LIST_FAILURE';


export const GET_INVIT_EVENT_LIST = 'GET_INVIT_EVENT_LIST';
export const GET_INVIT_EVENT_LIST_SUCCESS = 'GET_INVIT_EVENT_LIST_SUCCESS';
export const GET_INVIT_EVENT_LIST_FAILURE = 'GET_INVIT_EVENT_LIST_FAILURE';